#pragma once
#ifndef PRINTF_CONFIG_H_
#define PRINTF_CONFIG_H_

#define PRINTF_SUPPORT_FLOAT_SPECIFIERS         0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS   0
#define PRINTF_SUPPORT_LONG_LONG                0
#define PRINTF_SUPPORT_PTRDIFF_LENGTH_MODIFIER  1
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES    0


#endif // PRINTF_CONFIG_H_

