function(ch_absolutize)
  unset(result)
  foreach(path ${ARGV})
    if(IS_ABSOLUTE "${path}")
      list(APPEND result "${CHIBIOS_ROOT}/${path}")
    else()
      list(APPEND result "${path}")
    endif()
  endforeach()
  gt_absolutize("${result}")
  set(result "${result}" PARENT_SCOPE)
endfunction()

function(ch_add_sources)
  unset(result)
  ch_absolutize("${ARGV}")
  gt_add_sources(${result})
endfunction()

function(ch_add_include_directories)
  unset(result)
  ch_absolutize("${ARGV}")
  gt_add_include_directories(${result})
endfunction()

function(ch_include target)
  unset(result)
  ch_absolutize("${ARGN}")
  gt_include(${target} "${result}")
endfunction()
