function(util_join_cl var command)
  set(result "${command}")
  if(${ARGC} GREATER 1)
    foreach(x ${ARGN})
      set(result "${result} ${x}")
    endforeach()
  endif()
  set(${var} "${result}" PARENT_SCOPE)
endfunction()
